### PR TITLE
Add a Vue.js webapp for visual comparisons of GS and GS Flex

### LINKED ISSUE #30: Comparison testing between Google Sans & Google Sans Flex
Google Sans will be used as a fallback font for Flex, so ensuring there aren't jarring differences between them would be useful

### PR DESCRIPTION
**Pull request by belluzj**
There are build instructions in the README.md file. The outcome of the `npm run build-only` is the attached HTML file: 
[index.zip](https://github.com/googlefonts/googlesans-flex/files/10059029/index.zip)

Open the file in a web browser e.g. by double-clicking it. It should display the following UI:

image

Drag-and-drop two fonts into the blue and red file selectors at the top, then use the sliders for Font Size and Overlay Offset to align the two fonts vertically, then use the axis sliders to compare the fonts at various locations.

Fixes https://github.com/googlefonts/googlesans-flex/issues/30

### CODE REVIEW

**Comment by RickyDaMa** [comment]
Could we add a shortcut in the Makefile to run the `npm` fat HTML build? Would be nice to keep everything in one place if possible. This way you could also depend on GS Flex being built, so you can ensure you're getting the latest sources

**Comment by belluzj** [comment]
@MariannaPaszkowska I added the instance dropdown, it looks like this: 
image

New index.html: [index.zip](https://github.com/googlefonts/googlesans-flex/files/10066510/index.zip)

**Comment by belluzj** [comment]
TODO: (Jany) Move to Dalton Maag organization, remove references to GS/Flex, make public

**Comment by belluzj** [comment]
@MariannaPaszkowska I'm working on this, and I wanted to confirm whether it's OK to refer to the name "flex" and to the axis tags and names of Google Flex, such as GRAD and ROND in the source code of the font tester? I will however remove all "Google", "Google Sans" or "GS" mentions.

Thanks in advance!

**Comment by belluzj** [comment]
I removed mentions of "flex", however the axis tags remain (they're hardcoded in the tester at the moment). If that's an issue, I could make the tester auto-detect the axes from the dropped fonts. Let me know and then I'll push to GitHub (I created the empty repository here: https://github.com/daltonmaag/overlay-font-tester)

**Comment by MariannaPaszkowska** [comment]
@belluzj Great idea! If the tool can auto-detect the axes from the dropped fonts, it makes it more universal. Let's implement it!

**Pull request closed without merging**
