### PR TITLE
Add more features

### PR DESCRIPTION
**Pull request by madig**
* Hook up ss01 and ss02 features for `a` and `g`.
* Remove spurious unused instance

@MariannaPaszkowska

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Ty! 🚀 

6JzL79pjATSkvtz

**Comment by madig** [comment]
Mind you that features currently aren't imported automatically, so if FB writes something, we need to import it manually.

**Comment by madig** [comment]
@MariannaPaszkowska @chrissimpkins I think this is ready for merging as of right now; the upstream sources have more of the needed glyphs, but as of right now, they don't build. The features can be enabled as soon as the sources are importable again.

**Comment by chrissimpkins** [comment]
~ superceded by #288

**Pull request closed without merging**
