### PR TITLE
Additional documentation for the build process

### LINKED ISSUE #696: Document the build steps required to compile GS Flex fonts
We are attempting to understand how much post-compile Python source will be required to get to the final font used for CI QA testing and releases as we begin to look into the replacement of fontmake with fontc.  Let's document the full end-to-end build process for GS Flex, including all of the steps that are required after the fontmake compile stage of the build.

Thanks!

cc @MariannaPaszkowska

### PR DESCRIPTION
**Pull request by RickyDaMa**
Will close #696 

Hope this is the sort of thing you were after Chris!

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thanks Ricky!

@rsheeter @anthrotype see Ricky's docs here for additional details about the scripts involved in the GS Flex build.

**Comment by rsheeter** [comment]
Ty!

QQ, why is font-v necessary? What does it set the version string from/to?

**Review by rsheeter — APPROVED** [review]
LGTM

**Review by chrissimpkins — APPROVED** [review]

**Comment by RickyDaMa** [comment]
@rsheeter it sets the current Git SHA in the version string:

image

**Pull request merged**
