### PR TITLE
Point UFOs to shared family.fea

### PR DESCRIPTION
**Pull request by madig**
This makes UFOs always point to the family.fea file next to the target Designspace to import into. All feature development should happen inside family.fea, and all changes need to be ported by hand.

@MariannaPaszkowska @chrissimpkins

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thanks Nikolaus!  Let's merge and try it.

**Comment by chrissimpkins** [comment]
I ran the updated importer against the latest fb-wip branch in https://github.com/googlefonts/googlesans-flex/actions/runs/4105413587

**Comment by chrissimpkins** [comment]
Mind deleting your branch here if it works as intended?

**Comment by madig** [comment]
Awww, incompatibilities again... Well, it works when testing locally, on fb-wip from 2 commits ago.

**Comment by madig** [comment]
Oh, just to make it clear, this will not import features, just point all UFOs to a shared family.fea file. Features need to be written and imported manually, there's no good way to automate this.

**Comment by chrissimpkins** [comment]
> Oh, just to make it clear, this will not import features, just point all UFOs to a shared family.fea file. Features need to be written and imported manually, there's no good way to automate this.

Np at all.  All features are implemented in the top level family.fea file and we'll manually edit the file with changes.  The goal was only to make sure that the feature code was imported into the masters via the individual UFO master features.fea files as required to compile them.

**Pull request merged**
