### PR TITLE
Update glyph list & check for missing or extraneous glyphs

### PR DESCRIPTION
**Pull request by RickyDaMa**
Willing to take suggestions on the name for this script, I can't think of a good concise one

Current output:
```
Missing the following glyphs (0):
-

The following glyphs in the source aren't in the import list (79):
- Eth-bar
- Euro.tf
- Oslash-bar
- a.alt
- approxequal.tf
- caroncomb.alt
- cent.tf
- colon.tf
- colon.time
- comma.tf
- currency.tf
- diagonalbarl
- divide.tf
- dollar.tf
- dot-composite
- eight.denominator
- eight.numerator
- eight.tf
- equal.tf
- exclam-bottom
- exclam-top
- five.denominator
- five.numerator
- five.tf
- flig1
- flig2
- four.denominator
- four.numerator
- four.tf
- g.alt
- greater.tf
- greaterequal-stroke
- greaterequal.tf
- horizontalbarlc
- less.tf
- lessequal.tf
- logicalnot.tf
- minus
- minus.tf
- multiply.tf
- nine.denominator
- nine.numerator
- nine.tf
- notequal
- notequal-slash
- notequal.tf
- numbersign.tf
- one.denominator
- one.numerator
- one.tf
- oslash-bar
- percent.tf
- percentbar
- percentbar.tf
- period.tf
- plus.tf
- plusminus.tf
- question-bottom
- question-top
- section.tf
- semicolon.tf
- seven.denominator
- seven.numerator
- seven.tf
- six.denominator
- six.numerator
- six.tf
- space.tf
- sterling.tf
- three.denominator
- three.numerator
- three.tf
- two.denominator
- two.numerator
- two.tf
- zero.denominator
- zero.numerator
- zero.tf
- zeropercent
```

### CODE REVIEW

**Comment by MariannaPaszkowska** [comment]
@RickyDaMa Is this ready for a review or still in progress?

**Comment by RickyDaMa** [comment]
Hi @MariannaPaszkowska, this is ready to merge and safe to put in! Nothing critical that I want peer review on

**Comment by MariannaPaszkowska** [comment]
@RickyDaMa, thanks! We have some conflicts now. Could you have a look?

**Comment by RickyDaMa** [comment]
@MariannaPaszkowska sorted!

**Pull request merged**
