### PR TITLE
Makefile: fix proof cmd

### PR DESCRIPTION
**Pull request by m4rc1e**
gen-html has been deprecated in favour of diffenator2.

My plan to fix this upstream is the following:

- Fix the ci for packaging gftools.
- add this commit to the original template.

Existing users of the googlefonts-project-template are currently ok since they're using gftools v0.9.21 which doesn't have the diffenator 2 update. It'll be broken for them as well if I fix the ci in gftools and don't update the template. Apologies for these issues. Went on holiday and forgot the state of most things.

fixes https://github.com/googlefonts/googlesans-flex/pull/241#issue-1532724211

### CODE REVIEW

**Review by RickyDaMa — APPROVED** [review]
Thanks Marc!

**Comment by RickyDaMa** [comment]
Added some commits to re-enable proofing on CI now. Tested it out locally, works fine, made some small tweaks to the gitignore and Makefile to keep things tidy

**Comment by m4rc1e** [comment]
Thanks Ricky!

**Comment by MariannaPaszkowska** [comment]
Thank you @m4rc1e, @RickyDaMa!

**Pull request merged**
