### PR TITLE
Import upstream as of Nov 21

### PR DESCRIPTION
**Pull request by madig**
This imports upstream GSF as of https://github.com/FontBureau/fb-GoogleSansFlex/tree/33ca300831df941d84725a96cd15f796e46fa4bd.

I imported only the uprights (the italics seem to not be ready?) and normalized them with the GS normalization script, deliberately skipping the UFOs that I didn't know what to do with:

* GoogleSansFlex-opsz144-wdth151-wght1000-ROND100 copy.ufo
* GoogleSansFlex-opsz144-wdth151-wght1000-ROND0-SO.ufo

I also wrote the script `rebuild-designspace.py`, which just re-registers all UFOs in the Designspace (thank you for the UFO naming 😬). I think this is the best way to handle the still evolving design space.

### CODE REVIEW

**Comment by dberlow** [comment]
Hard to figure shouldn’t really be a problem unless the design space file is ignored.

Are you using the design space file to build this font or are you just ignoring it?

**Comment by madig** [comment]
I found neither in `GoogleSansFlex[opsz][wdth][wght].designspace`, which also doesn't list the ROND100 UFOs. I just made a new one, registering all upright UFOs except those two. Do you keep a different Designspace somewhere else?

**Comment by MariannaPaszkowska** [comment]
This was closed unintentionally, reopening.

**Comment by dberlow** [comment]
Looking at the Google Google sans flex repository, looks old, and not as tidy as fb’s repo, So it looks like our latest data is not getting to you. 

Six days ago, this design space was committed to our repo:

https://github.com/FontBureau/fb-GoogleSansFlex/blob/main/sources/roman/GoogleSansFlex%5Bopsz%5D%5Bwdth%5D%5Bwght%5D.designspace

**Comment by dberlow** [comment]
We are pushing on fb repo data onto our google branch now.

my apologies that was not done and I will make sure that it is done daily now.

**Comment by MariannaPaszkowska** [comment]
Closing this PR, we will use the automated process instead.

**Pull request closed without merging**
