### PR TITLE
Import, but with /dollar from v2.003

### PR DESCRIPTION
**Pull request by Hoolean**
This PR contains the changes from the last test import (`import-GSF-Ashler-v2.4`) but with the outlines of /dollar reverted to those from v2.003 (e6bc8a20a00c17c7853fbf50581ef9c2154e8187).

### CODE REVIEW

**Comment by MariannaPaszkowska** [comment]
@Hoolean, I think we should revert the import where we merged Octavio's liga work, so we have the least diffs in the 2.004 release.

**Comment by Hoolean** [comment]
Sounds good - are there any source changes on `main` since the v2.003 release that we need to actively roll back, or do we just need to close this PR? Looking [at what has landed](https://github.com/googlefonts/googlesans-flex/compare/v2.003...main), we might only have pipeline changes on our `main` branch since then :)

**Comment by Hoolean** [comment]
I've now reviewed the diff between v2.003 and current `main`: there are a few changes, but we have not done a full import since the last release.

### Diffy changes

* Update requirements
     - Makefile
     - requirements.txt
     -  sources/config.yaml

* Increase WinAscender
    - sources/GoogleSansFlex-*.ufo/fontinfo.plist

### Non-diffy changes

* Workflow updates:
    -  .github/
    -  qa/
    -  scripts/

* Syncing **design** sources (not UFOs)
    - sources/design-source/GSF-full.glyphspackage/

**Comment by Hoolean** [comment]
Which if any of the diffy changes do we want to rollback before the workspace fix release?

- Update requirements
  - [x] Do not rollback, as these will be replaced by the version bump we do to get the fonttools fix anyway
- Increase WinAscender
  - [x] ~Consider rolling back?~
      My local tags were outdated, this has already been released and so should potentially stay as-is

**Pull request closed without merging**
