### PR TITLE
Import workflow: add OTS check

### PR DESCRIPTION
**Pull request by RickyDaMa**
Follow up to #217 & #218, runs OT Sanitiser as part of the import workflow (otherwise wouldn't happen because of previously discussed workflows triggering workflows problems)

@chrissimpkins I presume this is something you'd like :) No need to merge otherwise

### CODE REVIEW

**Comment by chrissimpkins** [comment]
The new workflow step [ran in the CI of the PR that I added yesterday](https://github.com/googlefonts/googlesans-flex/pull/218#issuecomment-1376437104).  I don't understand why it needs to be on the import workflow.  When a new imported commit lands in a new branch do we not trigger the build workflow?  Can you explain in a bit more detail?

**Comment by RickyDaMa** [comment]
It depends on when you want OTS to run

If you use the import workflow and subsequently create a PR, OTS is not run on that PR without this PR being merged prior

Everything you want to be done on an import PR has to be included in the import workflow directly, as otherwise it's not automatically triggered. That's why the `.github/workflows/import.yaml` does it all: it imports, merges, commits, pushes, builds, tests, QAs, and runs file size analysis. It's not a good system, but it's what we're stuck with until we discuss solutions in a retrospective

**Comment by chrissimpkins** [comment]
Got it!  Thank you very much Ricky.  Let's merge this.  Please let me know if you feel that it should be removed from the build.yml file.

**Comment by RickyDaMa** [comment]
No harm in keeping it in the `build.yaml`. I'd rather keep that file maintained and then hopefully we can start using it properly again soon

**Pull request merged**
