### PR TITLE
Add "wiggle" graphical ligature feature support

### LINKED ISSUE #344: Add wiggle code to calt feature
Add to calt:
```
sub colon asciitilde by wiggle;
sub wiggle asciitilde' by wiggle;
```

### PR DESCRIPTION
**Pull request by chrissimpkins**
related #287

### CODE REVIEW

**Comment by chrissimpkins** [comment]
The input string is still being debated.  Will keep open as draft for now.

**Comment by chrissimpkins** [comment]
Adjusted the input string to the following in https://github.com/googlefonts/googlesans-flex/pull/318/commits/9361a8fe41a08628b0e6a8248d84a323e1f44044

`:~` is first wave
`:~~` is second wave
`:~~~` is third wave
... ad infinitum

Still under review/discussion

**Comment by chrissimpkins** [comment]
wiggle

**Comment by MariannaPaszkowska** [comment]
Let's add this code to calt: #344

**Comment by chrissimpkins** [comment]
> Let's add this code to calt: https://github.com/googlefonts/googlesans-flex/issues/344

addressed in https://github.com/googlefonts/googlesans-flex/pull/318/commits/90166b7de5eef5c7094a7fbad8056fd90913e827

**Comment by chrissimpkins** [comment]
This PR now includes the approved wiggle ligature input string in the calt feature.  Ready to merge.

**Pull request merged**
