### PR TITLE
Update build dependencies

### PR DESCRIPTION
**Pull request by RickyDaMa**
Updates build dependencies to the latest at the time of commit. I was going to update Python to 3.12, but it seems to significantly increase built & test times

Most recent diffenator run: [here](https://github.com/googlefonts/googlesans-flex/actions/runs/10268362064) - no changes!

### CODE REVIEW

**Comment by RickyDaMa** [comment]
Both builds and tests now seem to be taking longer 🤔 

I've increased the timeout for tests, but this'll only kick in after the PR is merged due to how the test workflow works

**Comment by RickyDaMa** [comment]
Tried to reproduce the performance difference locally, failed:

image

<details>
<summary>hyperfine invocation used</summary>

```shell
hyperfine --warmup 1 --runs 4 \
  -n "Python 3.11 old deps" "venv/bin/gftools builder sources/config-old.yaml" \
  -n "Python 3.11 new deps" "venv311-new-deps/bin/gftools builder sources/config.yaml" \
  -n "Python 3.12 new deps" "venv312/bin/gftools builder sources/config.yaml"
```

</details>

**Comment by MariannaPaszkowska** [comment]
let's stick to python 3.11 and let's review if the PR reflects this. cc @RickyDaMa

**Comment by RickyDaMa** [comment]
PR is all good and updated, only failing the pipeline because of #1016

**Comment by MariannaPaszkowska** [comment]
I confirm no differences. Many thanks!

**Pull request merged**
