### PR TITLE
Troubleshooting GitHub workflows: simplify `runs-on`

### PR DESCRIPTION
**Pull request by RickyDaMa**
Suggested [here](https://github.com/googlefonts/googlesans-flex/issues/961#issuecomment-2217884584)

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@RickyDaMa This workflow still seems to hang on location of a runner

https://github.com/googlefonts/googlesans-flex/actions/runs/9859106585/job/27222255005?pr=962

Did we miss a definition?

**Comment by chrissimpkins** [comment]
Seems to still be attempting with:

Requested labels: linux, googlefonts-64cores-256GB

**Comment by RickyDaMa** [comment]
Tests use the workflow definition from the `main` branch, which has the old declaration. The issue would resolve itself when this PR is merged

**Comment by chrissimpkins** [comment]
I canceled the hung runner.  Will merge. Can we test that that runner workflow does run in main branch?

**Comment by RickyDaMa** [comment]
> Can we test that that runner workflow does run in main branch?

The workflow that runs on `main` will demonstrate everything is working

https://github.com/googlefonts/googlesans-flex/actions/runs/9859595289

**Pull request merged**
