### PR TITLE
Rewrite diffenator2 workflow

### PR DESCRIPTION
**Pull request by RickyDaMa**
Based on GS Mono: https://github.com/googlefonts/googlesans-mono/blob/5cf114eb8a5a8314de39f64d40638dc7c4dab986/.github/workflows/diffenator2.yml

Let's you compare two arbitrary points in Git history without requiring special branch names

Due to https://github.com/googlefonts/diffenator2/issues/134, the current workflow doesn't work any more now that our releases have statics

### CODE REVIEW

**Review by m4rc1e — APPROVED** [review]
LGTM

I've never used a workflow dispatch! This looks great.

I haven't checked for typos etc but I'm sure these can be fixed once merged. Personally, I've never found a good way to test github actions. I usually just test run them on a fork until it works, then merge all the testing commits together.

**Comment by RickyDaMa** [comment]
> Personally, I've never found a good way to test github actions.

Yep, same. We (Dalton Maag) have private forks of the big Google repos; I've tested this workflow here and it was fine in a basic smoke check ✅

**Comment by m4rc1e** [comment]
I'm on holiday next week but when I come back, I'll alter the diffenator2 github action so you can specify which archive to use in a release.

**Comment by RickyDaMa** [comment]
Enjoy your break!

No rush on that feature - I think we should stick with the approach in this PR in any case because then we're not limited to only testing against the previous release. Ultimately though, that's for Marianna to decide on

**Pull request merged**
