### PR TITLE
Progress burndown chart

### PR DESCRIPTION
**Pull request by belluzj**
Implements #73.

Todo: 
* [ ] Better define the expected numbers of UFOs for the upcoming milestones (to have more accurate slanted lines)
* [ ] Integrate into a GitHub workflow

### CODE REVIEW

**Comment by belluzj** [comment]
Here is a preview of the output of the script, on a test branch that I prepared with fake progress:

Roman_-_version_1 000_counts
Roman_-_version_1 000_progress

The colored area in the middle is the range of commits that have mark colors. In the first graph, all glyph statuses are given equal importance, and in theory if all the UFOs exist and all contain the target glyph set, the colored area should be as tall as the blue line (except in case of sparse sources; to be refined if that's the case). It's up to the reader of the graph to interpret that yellow glyphs are only halfway done.

The second graph is scaling the glyph statuses by a "progress percentage", so green glyphs = done are shown full height, yellow glyphs = 50% done are shown half-height, and not started yet glyphs (red) are not shown at all.

The script takes in [a configuration object](https://github.com/googlefonts/googlesans-flex/pull/76/files#diff-e16709e3e926d793c7c80e42c2575346ea1b42bbfda15bb96b52468cadd98ed5R69-R110) that defines:

* which range of commits to analyze
* for each milestone:
    * start and due dates, to draw the blue line
    * target number of glyphs and UFOs, to set the top-right corner of the blue line (glyphs * UFOs)
    * a filter to know in which UFOs to look for colors (e.g. to make a milestone only about uprights)
    * a list of possible glyph statuses, with the mark color to use for matching them.
 
We can adjust the configuration when once we know the exact mark colors that the FB team will be using to annotate progress; for now I've used retina-burning pure RGB colors.

Let us know what you think.

**Comment by belluzj** [comment]
Here is the current result on fb-wip:
Roman_-_version_1 000_counts

I have solved the question of the exact mark colors by using the "colorsys" python module from the standard library to extract the hue of the mark colors and categorize the ones currently in use:
image


I have a new question now related to the target amount of glyph instances:
* either we could "predict" the target amount by computing number of glyphs * number of UFOs
  * doesn't work for sparse sources (they have fewer glyphs than a full source)
  * is the final number of UFOs already decided?
* or we could measure what we find on the branch, but it makes the target "move" with the state of the branch.

**Comment by belluzj** [comment]
For now:

- [ ] ignore sparse sources
- [x] put all milestones on the same graph

For the future:
* differentiate composite vs drawn, assign smaller weight to composites in the diagram
* try to speed up

**Comment by belluzj** [comment]
@MariannaPaszkowska @chrissimpkins I have a question about the target number of main sources for the v1.000 and v1.100 milestones: do you know how many UFOs will be used to support the GRAD axis? Will GRAD-50 and GRAD50 variant be drawn for all GRAD0 sources, or will only some of the GRAD0 sources get matching GRAD-50 and GRAD50? If so, do you know which? Thanks in advance!

**Comment by belluzj** [comment]
I have improved the output a bit, see below:

gs-flex-progress


The targets for each milestone are still not clear to me, in terms of how many UFOs are planned in total.

Next we could generate this graph as part of the push workflow to fb-wip? Or maybe with a manual trigger, if you don't want to generate it on each push? The script currently takes 2 minutes 30 to run on my machine.

@MariannaPaszkowska @chrissimpkins let us know what you would prefer.

**Comment by MariannaPaszkowska** [comment]
@belluzj January release is planned to support all axes: wght, wdth, ROND and GRAD (and only Roman). I expect 120 basic masters (+some sparse masters). 

Let's generate this graph on each push.

**Comment by belluzj** [comment]
Updated with the expectation of 120 UFOs for v1.000 (and 120*2 for v1.100, because of the italic):

gs-flex-progress

@madig will automate this as part of a GitHub action on fb-wip.

**Comment by madig** [comment]
I added a workflow, but it does not seem to trigger. Maybe it needs to be in main first? @chrissimpkins @MariannaPaszkowska I suppose this is ready for review and merging?

**Comment by MariannaPaszkowska** [comment]
Thank you @belluzj, @madig!

**Pull request merged**
