### PR TITLE
fixes issue in dollar and cent (Issue #936)

### PR DESCRIPTION
**Pull request by octaviopardo**

### CODE REVIEW

**Comment by MariannaPaszkowska** [comment]
Hi @octaviopardo I'm reviewing this PR and I see two new encoded glyphs
̵
̷

are those intentional or is this caused by that old issue where non-exporting glyphs sneak in? 
cc @belluzj @RickyDaMa

**Comment by octaviopardo** [comment]
Both glyphs are set to non-export

Captura de pantalla 2024-05-14 a las 18 11 08

**Comment by MariannaPaszkowska** [comment]
@RickyDaMa @belluzj Did we unintentionally change something in the latest update? Non-exporting glyphs are in the build fonts now.

**Comment by RickyDaMa** [comment]
Last I recall, we haven't done an import since fixing the issue, so the UFO sources will still be built with all glyphs, not respecting those marked as excluded in the design/Glyphs sources

In any case, we'll need to run the import workflow on the changes in this PR, so then everything should come out in the wash

**Comment by MariannaPaszkowska** [comment]
Of course! I forgot to import. That was silly of me! Thanks a lot @RickyDaMa !

**Comment by MariannaPaszkowska** [comment]
fixed in import #947

**Pull request closed without merging**
