### PR TITLE
ufodiff on CI

### PR DESCRIPTION
**Pull request by RickyDaMa**
Uses a docker-based GitHub action to run ufodiff on the repo.

~~Currently configured to compare against master on branches called `import-*` (* being anything)~~ Runs on all pushes to branches except `main`

Keeping as draft until I know it works as intended

### CODE REVIEW

**Comment by RickyDaMa** [comment]
Hi Chris & Marianna!

This PR will add a CI step to run [ufodiff](https://github.com/source-foundry/ufodiff) on every push that isn't to `main` and builds successfully. Currently, this is configured to compare against `main`, telling you what glyphs have been added/updated/deleted.

This is achieved using a GitHub action I wrote, which lives in this repository at `.github/actions/ufodiff`. I chose to keep it in this repository as it doesn't really feel suitable for general use (it's not really a tool designed to be used in CI), so there's not much point in making this more open. The GitHub action works by checking out the repository, then ufodiff is run on it (through a Docker container).

I have chosen to create a separate GitHub workflow (note: workflow != action) to run this program in, as part of a to-be-expanded regression testing suite. This makes little difference to how you interact with the workflow, it just means it can be triggered differently to the existing build and release workflow (because I don't want ufodiff running on `main`). The downside here is that I'm not actually able to test that the final state of this PR (as of the time of writing) is configured correctly. That is because GitHub won't let workflows trigger workflows (which is how this new regression suite works) unless they're on the default branch (i.e. `main`) ([citation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run), see 2nd note box). I have tested it through other means and am confident it should work as expected once merged. We would then be able to use it to see what's changed with #35, once that PR builds.

If desired, I can add a means to run this action locally, however I'm not sure there's much of a value proposition to that when you could just use ufodiff directly instead of faffing with Docker. I do already have something mostly jerry-rigged together though, as I needed it for testing.

Apologies for the small essay, interested to hear your thoughts!

(Related issue #27)

**Comment by chrissimpkins** [comment]
ufodiff is unmaintained at this stage.  IMO I would not rely on it in this project unless someone is prepared to maintain it.

**Comment by RickyDaMa** [comment]
For now we'd like to use ufodiff initially as it's a good already-existing starting point (that works currently even if it's not seeing active development/maintenace). We can evaluate later on if the metrics/output it provides is useful on the next source update PR, and if it's something that is a value-add, we can consider taking on the maintenance burden or writing a simplified/bespoke version for GS Flex.

What do you think @chrissimpkins?

**Comment by chrissimpkins** [comment]
Sgtm!

**Comment by RickyDaMa** [comment]
@chrissimpkins @MariannaPaszkowska 

If you guys are happy, you are most welcome to merge whenever :)

**Comment by MariannaPaszkowska** [comment]
Thank you, @RickyDaMa!

**Pull request merged**
